import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { openBrowser } from './browser-helpers.mjs';
const app = await openBrowser(); const { page, browser, url } = app; const errors = []; page.on('pageerror', e => errors.push(e.message));
const field = n => page.locator(`[data-field="${n}"]`), button = n => page.locator(`[data-action="${n}"]`), steps = () => page.locator('.hide-seek').getAttribute('data-steps').then(Number);
try {
  assert.equal(await page.locator('canvas').count(), 1);
  await field('speed').selectOption('48'); await button('play').click(); await page.waitForFunction(() => Number(document.querySelector('.hide-seek').dataset.steps) >= 30); await button('play').click(); const paused = await steps(); await page.waitForTimeout(200); assert.equal(await steps(), paused);
  await button('reset').click(); await button('play').click(); await page.waitForFunction(() => ['tagged','escaped'].includes(document.querySelector('.hide-seek').dataset.phase)); assert.ok(await steps() > 24); await button('reset').click(); assert.equal(await steps(), 0); await button('step').click(); assert.equal(await steps(), 1);
  await field('model').selectOption('initial'); assert.equal(await steps(), 0); assert.equal(await page.locator('[data-eval="seeker"]').textContent(), '—'); await button('play').click(); await page.waitForTimeout(400); await button('play').click(); assert.ok(await steps() > 3);
  await field('model').selectOption('trained'); await field('vision').selectOption('seeker'); await button('left').click(); await button('right').click(); await button('zoom-in').click(); await button('zoom-out').click();
  await field('width').fill('20'); await field('height').fill('20'); await field('count').fill('12'); await field('seed').fill('89211'); await button('generate').click(); assert.match(await page.locator('.hs-seed-label').textContent(), /89211/);
  await field('width').fill('25'); await button('generate').click(); assert.match(await page.locator('.hs-status').textContent(), /10–20/); await field('width').fill('14'); await field('height').fill('12'); await field('count').fill('0'); await field('seed').fill('2709'); await button('generate').click();
  await page.locator('.hs-editor summary').click(); await field('x').fill('2'); await field('y').fill('2'); await field('bw').fill('1'); await field('bh').fill('1'); await button('add').click(); assert.equal(await field('block').locator('option').count(), 2);
  await field('block').selectOption('0'); await field('x').fill('3'); await button('move').click(); assert.match(await field('block').locator('option').nth(1).textContent(), /3, 2/);
  await field('block').selectOption('0'); await button('remove').click(); assert.equal(await field('block').locator('option').count(), 1);
  // Place a block through the actual 3D ground picker, then remove it through the keyboard controls.
  await field('edit').selectOption('place'); await page.locator('canvas').scrollIntoViewIfNeeded();
  await page.locator('canvas').click({position:{x:(await page.locator('canvas').boundingBox()).width*.45,y:(await page.locator('canvas').boundingBox()).height*.5}});
  assert.equal(await field('block').locator('option').count(),2); await field('block').selectOption('0'); await button('remove').click(); await field('edit').selectOption('orbit');
  await page.locator('.hs-files summary').click();
  const [arenaDownload] = await Promise.all([page.waitForEvent('download'), button('export-arena').click()]); const arena = JSON.parse(await fs.readFile(await arenaDownload.path(), 'utf8')); assert.equal(arena.width, 14); assert.equal(arena.blocks.length, 0);
  const [modelDownload] = await Promise.all([page.waitForEvent('download'), button('export-model').click()]); const model = await fs.readFile(await modelDownload.path(), 'utf8'); assert.equal(JSON.parse(model).policies.length, 2);
  await page.locator('.hs-file').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{bad') }); await page.waitForFunction(() => document.querySelector('.hs-status').textContent.startsWith('Import failed'));
  await page.locator('.hs-file').setInputFiles({ name: 'model.json', mimeType: 'application/json', buffer: Buffer.from(model) }); await page.waitForFunction(() => document.querySelector('.hide-seek').dataset.model === 'imported'); assert.equal(await page.locator('[data-eval="seeker"]').textContent(), '—');
  await field('model').selectOption('trained'); await page.locator('.hs-file').setInputFiles({ name: 'arena.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...arena, seed: 98221 })) }); await page.waitForFunction(() => document.querySelector('.hs-seed-label').textContent.includes('98221'));
  // A slow file read cannot overwrite a later reset/generation.
  await page.evaluate(() => { window.__nativeText = File.prototype.text; File.prototype.text = function () { return new Promise(resolve => { window.__finishRead = () => window.__nativeText.call(this).then(resolve); }); }; });
  await page.locator('.hs-file').setInputFiles({ name: 'late.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...arena, seed: 111 })) }); await field('seed').fill('222'); await button('generate').click(); await page.evaluate(() => window.__finishRead()); await page.waitForTimeout(100); assert.match(await page.locator('.hs-seed-label').textContent(), /222/); await page.evaluate(() => File.prototype.text = window.__nativeText);
  // Full selected speed text has room at desktop and both narrow phone widths.
  for (const width of [1280, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 }); await field('speed').selectOption('48'); await field('speed').scrollIntoViewIfNeeded();
    const dimensions = await field('speed').evaluate(el => { const s = getComputedStyle(el), c = document.createElement('canvas').getContext('2d'); c.font = s.font; return { text: c.measureText(el.selectedOptions[0].textContent).width, available: el.clientWidth - parseFloat(s.paddingLeft) - parseFloat(s.paddingRight), page: document.documentElement.scrollWidth, viewport: innerWidth }; }); assert.ok(dimensions.available >= dimensions.text + 6, JSON.stringify(dimensions)); assert.ok(dimensions.page <= dimensions.viewport, JSON.stringify(dimensions));
    await page.screenshot({ path: `test-results/mobile-${width}.png` });
  }
  // The batched false/true observer delivery must use its final visibility entry.
  const isolated = await browser.newPage({ viewport: { width: 1280, height: 1000 } }); const isolatedErrors = []; isolated.on('pageerror', e => isolatedErrors.push(e.message));
  await isolated.addInitScript(() => { window.__observers = []; window.IntersectionObserver = class { constructor(callback) { this.callback = callback; window.__observers.push(this); } observe(target) { this.target = target; } disconnect() {} }; });
  await isolated.goto(url); await isolated.locator('[data-ready="true"]').waitFor(); await isolated.evaluate(() => { const o = window.__observers[0]; o.callback([{ target: o.target, isIntersecting: false }, { target: o.target, isIntersecting: true }]); }); await isolated.locator('[data-action="play"]').click(); await isolated.waitForFunction(() => Number(document.querySelector('.hide-seek').dataset.steps) >= 5); assert.equal(isolatedErrors.length, 0);
  // Disposing a mounted app while File.text rejects must not touch removed DOM.
  await isolated.evaluate(async () => { const { mountExperiment } = await import('/src/index.js'); const host = document.createElement('div'); document.body.append(host); const instance = mountExperiment(host, { embedded: true }); File.prototype.text = () => new Promise((_, reject) => { window.__rejectRead = reject; }); const input = host.querySelector('input[type=file]'), transfer = new DataTransfer(); transfer.items.add(new File(['{}'], 'pending.json')); input.files = transfer.files; input.dispatchEvent(new Event('change', { bubbles: true })); instance.dispose(); window.__rejectRead(new Error('delayed read rejected')); host.remove(); }); await isolated.waitForTimeout(150); assert.equal(isolatedErrors.length, 0);
  const pixels = await isolated.evaluate(async () => { const { createView } = await import('/src/renderer.js'); const { generateArena } = await import('/src/core/arena.js'); const result = []; for (const transparent of [false, true]) { const host = document.createElement('div'); host.style = 'width:700px;height:500px'; document.body.append(host); const v = createView(host, { transparent }); v.setArena(generateArena()); const gl = host.querySelector('canvas').getContext('webgl2'), pixel = new Uint8Array(4); gl.readPixels(0, 0, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, pixel); result.push(pixel[3]); v.dispose(); host.remove(); } return result; }); assert.deepEqual(pixels, [255,0]); await isolated.close();
  const missing = await browser.newPage(); await missing.route('**/models/hide-seek.json', route => route.fulfill({ status:404, body:'missing' })); await missing.goto(url); await missing.waitForFunction(() => document.querySelector('.hs-status').textContent.startsWith('Unable to start:')); assert.equal(await missing.locator('[data-action="play"]').isDisabled(), true); await missing.close();
  assert.deepEqual(errors, []); console.log('Browser passed: learned/initial movement, pause/reset, editing, exports/imports, stale read/disposal, batched visibility, 320/390px and speed fit.');
} finally { await app.close(); }
