import assert from 'node:assert/strict';import fs from 'node:fs/promises';import{openBrowser}from'./browser-helpers.mjs';
await fs.mkdir('test-results',{recursive:true});const app=await openBrowser(),{page,browser,url}=app,errors=[];page.on('pageerror',e=>errors.push(e.stack));
const field=n=>page.locator(`[data-field="${n}"]`),button=n=>page.locator(`[data-action="${n}"]`),steps=()=>page.locator('.hide-seek').getAttribute('data-steps').then(Number),status=()=>page.locator('.hs-status').textContent();
const format='original-mujoco-persistent-buttons-ppo-v1';
async function exportJSON(action){const[download]=await Promise.all([page.waitForEvent('download'),button(action).click()]);return JSON.parse(await fs.readFile(await download.path(),'utf8'));}
async function record96(){await page.evaluate(()=>{for(let i=0;i<96;i++)document.querySelector('[data-action="step"]').click();});return exportJSON('export-replay');}
try{
 assert.equal(await page.locator('.hide-seek').getAttribute('data-policy-format'),format);assert.equal(await page.locator('.hs-ready-badge').textContent(),'DEVELOPMENT');assert.match(await page.locator('.hs-training-record').textContent(),/37,036,032/);assert.match(await page.locator('.hs-eval-note').first().textContent(),/remain unproven/);assert.match(await page.locator('.hs-eval-note').first().textContent(),/96 maps reused/);assert.match(await page.locator('.hs-training-record').textContent(),/15,990,784/);
 // Real UI actions must match the persistent actor directly, including its two
 // own requested inputs. A reset must clear both memories and both button pairs.
 await page.locator('.hs-files summary').click();
 const candidate=await exportJSON('export-model');assert.equal(candidate.observationSize,140);assert.equal(candidate.physicsObservationSize,138);
 const first=await record96();await button('reset').click();const repeated=await record96();assert.deepEqual(repeated.actions,first.actions);assert.equal(first.policyFormat,format);
 const expected=await page.evaluate(async({model,arena})=>{
   const[{createPersistentPolicies},{PhysicsSimulation,Random},{loadPhysics}]=await Promise.all([import('/src/core/persistentPolicy.js'),import('/src/core/physics.js'),import('/src/core/loadPhysics.js')]);
   const simulation=new PhysicsSimulation(await loadPhysics(),arena),actors=createPersistentPolicies(model),states=actors.map(actor=>actor.initialState()),random=new Random(arena.seed^0x9e3779b9),actions=[];
   try{for(let tick=0;tick<96;tick++){simulation.step(actors.map((actor,role)=>{const out=actor.act(simulation.observe(role),states[role],{deterministic:false,random:()=>random.next()});states[role]=out.state;return Array.from(out.action);}));actions.push(simulation.actions.map(action=>Array.from(action)));}return actions;}finally{simulation.dispose();}
 },{model:candidate,arena:first.arena});assert.deepEqual(first.actions,expected);assert(first.actions.slice(0,80).every(pair=>pair[1].every(value=>value===0)));
 await field('model').selectOption('initial');await page.waitForFunction(()=>document.querySelector('.hide-seek').dataset.model==='initial');await page.evaluate(()=>{for(let i=0;i<12;i++)document.querySelector('[data-action="step"]').click();});await field('model').selectOption('trained');await page.waitForFunction(()=>document.querySelector('.hide-seek').dataset.model==='trained');assert.deepEqual((await record96()).actions,first.actions);
 await page.locator('.hs-file').setInputFiles({name:'persistent-replay.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(first))});await page.waitForFunction(()=>document.querySelector('.hide-seek').dataset.replay==='true');await button('step').click();await button('reset').click();assert.deepEqual((await record96()).actions,first.actions);await field('model').selectOption('trained');await page.waitForFunction(()=>document.querySelector('.hide-seek').dataset.replay==='false');assert.equal(await steps(),0);await page.locator('.hs-files summary').click();
 assert.equal(await page.locator('canvas').count(),1);await field('speed').selectOption('4');await button('play').click();await page.waitForFunction(()=>Number(document.querySelector('.hide-seek').dataset.steps)>30);await button('play').click();const paused=await steps();await page.waitForTimeout(200);assert.equal(await steps(),paused);
 await button('reset').click();await button('play').click();await page.waitForFunction(()=>document.querySelector('.hide-seek').dataset.phase==='finished',null,{timeout:15000});assert.equal(await steps(),240);await button('reset').click();await button('step').click();assert.equal(await steps(),1);
 await field('tools').selectOption('off');assert.equal(await steps(),0);await button('step').click();assert.equal(await page.locator('.hide-seek').getAttribute('data-grabs'),'0');await field('tools').selectOption('fixed');assert.equal(await page.locator('[data-stat="tools"]').textContent(),'0 / 4');await field('tools').selectOption('on');
 await field('model').selectOption('initial');await page.waitForFunction(()=>document.querySelector('.hide-seek').dataset.model==='initial'&&document.querySelector('.hide-seek').dataset.ready==='true');assert.match(await page.locator('.hs-ready-badge').textContent(),/UNTRAINED/);await field('sampling').selectOption('sample');await button('step').click();assert.equal(await steps(),1);await field('model').selectOption('trained');await page.waitForFunction(()=>document.querySelector('.hide-seek').dataset.model==='trained'&&document.querySelector('.hide-seek').dataset.ready==='true');await field('sampling').selectOption('mean');
 await field('vision').selectOption('hider');await field('camera').selectOption('0');await button('left').click();await button('zoom-in').click();await field('camera').selectOption('none');await field('vision').selectOption('none');
 await field('scenario').selectOption('open');await field('count').fill('0');await field('ramps').fill('0');await field('seed').fill('89211');await button('generate').click();assert.match(await page.locator('.hs-seed-label').textContent(),/89211/);
 await field('size').fill('30');await button('generate').click();assert.match(await status(),/6–12/);await field('size').fill('8');await button('generate').click();
 await page.locator('.hs-editor summary').click();await field('x').fill('4');await field('y').fill('4');await button('add').click();assert.equal(await field('object').locator('option').count(),2);
 await field('object').selectOption('0');await field('x').fill('4.5');await field('yaw').fill('45');await button('move').click();assert.match(await field('object').locator('option').nth(1).textContent(),/4.5, 4.0/);await field('object').selectOption('0');await button('remove').click();assert.equal(await field('object').locator('option').count(),1);
 await field('kind').selectOption('ramp');await field('x').fill('4');await field('y').fill('4');await field('yaw').fill('0');await button('add').click();assert.equal(await field('object').locator('option').count(),2);await field('object').selectOption('0');await button('remove').click();
 await field('kind').selectOption('box');await field('edit').selectOption('place');await page.locator('canvas').scrollIntoViewIfNeeded();const rect=await page.locator('canvas').boundingBox();await page.locator('canvas').click({position:{x:rect.width*.5,y:rect.height*.55}});assert.equal(await field('object').locator('option').count(),2,await status());await field('edit').selectOption('orbit');
 await page.locator('.hs-files summary').click();const [sceneDownload]=await Promise.all([page.waitForEvent('download'),button('export-scene').click()]);assert.match(sceneDownload.suggestedFilename(),/\.png$/);
 const [arenaDownload]=await Promise.all([page.waitForEvent('download'),button('export-arena').click()]);const arena=JSON.parse(await fs.readFile(await arenaDownload.path(),'utf8'));assert.equal(arena.format,'hide-seek-physical-arena-v1');assert.equal(arena.objects.length,1);
 const [modelDownload]=await Promise.all([page.waitForEvent('download'),button('export-model').click()]);const model=await fs.readFile(await modelDownload.path(),'utf8');assert.equal(JSON.parse(model).actors.length,2);assert.equal(JSON.parse(model).format,format);
 await button('step').click();await button('step').click();const [replayDownload]=await Promise.all([page.waitForEvent('download'),button('export-replay').click()]);const replay=JSON.parse(await fs.readFile(await replayDownload.path(),'utf8'));assert.equal(replay.actions.length,2);
 await page.locator('.hs-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.waitForFunction(()=>document.querySelector('.hs-status').textContent.startsWith('Import failed'));
 await page.locator('.hs-file').setInputFiles({name:'model.json',mimeType:'application/json',buffer:Buffer.from(model)});await page.waitForFunction(()=>document.querySelector('.hide-seek').dataset.model==='imported');assert.match(await page.locator('.hs-training-record').textContent(),/not been verified/);
 // An explicitly labelled legacy binary fixture still imports as binary.
 const legacy=structuredClone(candidate);legacy.format='original-mujoco-recurrent-ppo-v1';legacy.observationSize=138;delete legacy.commands;
 for(const actor of legacy.actors){actor.observationSize=138;actor.weights['encoder.weight']=actor.weights['encoder.weight'].map(row=>row.slice(0,138));actor.weights['tools.weight']=actor.weights['tools.weight'].slice(0,2);actor.weights['tools.bias']=actor.weights['tools.bias'].slice(0,2);}
 await page.locator('.hs-file').setInputFiles({name:'legacy-binary-fixture.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await page.waitForFunction(()=>document.querySelector('.hs-status').textContent.includes('legacy binary'));assert.equal(await page.locator('.hide-seek').getAttribute('data-policy-format'),legacy.format);await button('step').click();assert.equal(await steps(),1);
 const unsupported={...legacy,format:'unsupported-policy'};await page.locator('.hs-file').setInputFiles({name:'unknown.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(unsupported))});await page.waitForFunction(()=>document.querySelector('.hs-status').textContent.startsWith('Import failed'));assert.equal(await page.locator('.hide-seek').getAttribute('data-policy-format'),legacy.format);
 await field('model').selectOption('trained');await page.locator('.hs-file').setInputFiles({name:'arena.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...arena,seed:98221}))});await page.waitForFunction(()=>document.querySelector('.hs-seed-label').textContent.includes('98221'));
 await page.locator('.hs-file').setInputFiles({name:'replay.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(replay))});await page.waitForFunction(()=>document.querySelector('.hide-seek').dataset.replay==='true');await button('play').click();await page.waitForFunction(()=>document.querySelector('.hs-status').textContent.includes('last saved decision'));assert.equal(await steps(),2);await button('reset').click();assert.equal(await steps(),0);
 // An earlier file read must never overwrite a later scene.
 await page.evaluate(()=>{window.__text=File.prototype.text;File.prototype.text=function(){return new Promise(resolve=>{window.__finishRead=()=>window.__text.call(this).then(resolve);});}});
 await page.locator('.hs-file').setInputFiles({name:'late.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...arena,seed:111}))});await field('seed').fill('222');await button('generate').click();await page.evaluate(()=>window.__finishRead());await page.waitForTimeout(100);assert.match(await page.locator('.hs-seed-label').textContent(),/222/);await page.evaluate(()=>File.prototype.text=window.__text);
 for(const width of [1280,390,320]){await page.setViewportSize({width,height:1000});await field('speed').selectOption('.5');await field('speed').scrollIntoViewIfNeeded();const d=await field('speed').evaluate(el=>{const s=getComputedStyle(el),c=document.createElement('canvas').getContext('2d');c.font=s.font;return{text:c.measureText(el.selectedOptions[0].textContent).width,available:el.clientWidth-parseFloat(s.paddingLeft)-parseFloat(s.paddingRight),page:document.documentElement.scrollWidth,viewport:innerWidth};});assert.ok(d.available>=d.text+6,JSON.stringify(d));assert.ok(d.page<=d.viewport,JSON.stringify(d));await page.screenshot({path:`test-results/physical-${width}.png`});}
 const isolated=await browser.newPage({viewport:{width:1280,height:1100}}),isolatedErrors=[];isolated.on('pageerror',e=>isolatedErrors.push(e.message));await isolated.addInitScript(()=>{window.__observers=[];window.IntersectionObserver=class{constructor(callback){this.callback=callback;window.__observers.push(this);}observe(target){this.target=target;}disconnect(){}};});await isolated.goto(url);await isolated.locator('[data-ready="true"]').waitFor();await isolated.evaluate(()=>{const o=window.__observers[0];o.callback([{target:o.target,isIntersecting:false},{target:o.target,isIntersecting:true}]);});await isolated.locator('[data-action="play"]').click();await isolated.waitForFunction(()=>Number(document.querySelector('.hide-seek').dataset.steps)>5);await isolated.locator('[data-action="play"]').click();
 // An invalid file import cancels an in-flight checkpoint load without stranding Play.
 let heldCheckpoint,signalCheckpoint;const checkpointRequested=new Promise(resolve=>signalCheckpoint=resolve);
 await isolated.route('**/models/physical-policy-initial-*.json',route=>{heldCheckpoint=route;signalCheckpoint();});
 await isolated.locator('[data-field="model"]').selectOption('initial');await checkpointRequested;
 await isolated.locator('.hs-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{invalid')});
 await isolated.waitForFunction(()=>document.querySelector('.hs-status').textContent.startsWith('Import failed'));
 assert.equal(await isolated.locator('[data-action="play"]').isEnabled(),true);
 await heldCheckpoint.continue();await isolated.waitForTimeout(100);assert.equal(await isolated.locator('.hide-seek').getAttribute('data-model'),'trained');
 await isolated.locator('[data-action="step"]').click();assert.ok(Number(await isolated.locator('.hide-seek').getAttribute('data-steps'))>0);
 // A pending default asset cannot replace a newer imported pair or reset its
 // physical/policy state. Disposal must also handle an unresolved model fetch.
 const modelFile=(await isolated.evaluate(async()=>{const m=await import('/src/core/policyAsset.js');return m.PHYSICAL_POLICY_FILE;}));
 let pendingDefault,signalDefault;let defaultRequested=new Promise(resolve=>signalDefault=resolve);
 await isolated.route(`**/${modelFile}`,route=>{pendingDefault=route;signalDefault();});
 const mountPending=()=>isolated.evaluate(async()=>{const{mountExperiment}=await import('/src/index.js');const host=document.createElement('div');host.id='pending-host';document.body.append(host);window.__pendingMount=mountExperiment(host,{embedded:true});});
 await mountPending();await defaultRequested;await isolated.locator('#pending-host [data-action="reset"]:enabled').waitFor();
 await isolated.locator('#pending-host .hs-file').setInputFiles({name:'newer-persistent.json',mimeType:'application/json',buffer:Buffer.from(model)});await isolated.locator('#pending-host [data-model="imported"]').waitFor();
 await isolated.evaluate(()=>{for(let i=0;i<5;i++)document.querySelector('#pending-host [data-action="step"]').click();});
 await pendingDefault.continue();await isolated.waitForFunction(()=>document.querySelector('#pending-host .hs-status').textContent.includes('Imported policies remain unverified'));
 assert.equal(await isolated.locator('#pending-host .hide-seek').getAttribute('data-model'),'imported');assert.equal(await isolated.locator('#pending-host .hide-seek').getAttribute('data-steps'),'5');
 await isolated.evaluate(()=>{window.__pendingMount.dispose();document.querySelector('#pending-host').remove();});
 defaultRequested=new Promise(resolve=>signalDefault=resolve);await mountPending();await defaultRequested;
 await isolated.evaluate(()=>window.__pendingMount.dispose());await pendingDefault.continue().catch(()=>{});await isolated.waitForTimeout(100);assert.equal(await isolated.locator('#pending-host .hide-seek').count(),0);await isolated.unroute(`**/${modelFile}`);
 await isolated.evaluate(async()=>{const{mountExperiment}=await import('/src/index.js');const host=document.createElement('div');host.id='dispose-host';document.body.append(host);window.__mounted=mountExperiment(host,{embedded:true});});await isolated.locator('#dispose-host [data-ready="true"]').waitFor();await isolated.evaluate(()=>{File.prototype.text=function(){return new Promise((_,reject)=>window.__rejectRead=()=>reject(Error('late failure')));};});await isolated.locator('#dispose-host .hs-file').setInputFiles({name:'late.json',mimeType:'application/json',buffer:Buffer.from('{}')});await isolated.evaluate(()=>{window.__mounted.dispose();window.__rejectRead();});await isolated.waitForTimeout(100);assert.deepEqual(isolatedErrors,[]);await isolated.close();assert.deepEqual(errors,[]);console.log('Browser passed: 96-step persistent actor/real-physics parity and reset/checkpoint/replay reproducibility, actual learned movement/full round, tools interventions, explicit legacy/invalid imports, camera/vision, props/editor picker, PNG/arena/model/replay files, late checkpoint/model/file reads and disposal, batched visibility, desktop/mobile320/390.');
}catch(error){await page.screenshot({path:'test-results/browser-failure.png'});console.error(await page.evaluate(()=>({status:document.querySelector('.hs-status')?.textContent,state:{...document.querySelector('.hide-seek')?.dataset},board:document.querySelector('.hs-board-shell')?.getBoundingClientRect().toJSON(),hidden:document.hidden})));console.error(errors);throw error;}finally{await app.close();}
